### ISSUE TITLE
Rename repo to `javascript`

### ISSUE THREAD

**Issue by seveibar** [seamapi/javascript#25]

**Comment by codetheweb** [comment]
@sybohy @dawnho what do people think about changing the way this is structured while we're at it?

Right now, the SDK and the [SDK tests](https://github.com/seamapi/seamapi-javascript-tests) are in separate repositories because we want to keep the tests private. However, this is annoying for a variety of reasons, including:
-  Tests can't be updated at the same time as a PR on this repo
- Having test pass/fail status inside a comment on PRs instead of a regular check feels weird

Instead, we could combine the two repositories (keep the SDK and tests in the same repo), make **that** repo private, then add a workflow that mirrors the private repo (minus the test folder) on every push to a public read-only repo. This has its own tradeoffs: which repo do we now make issues on? Do we allow users to directly make issues on the public repo? And we'd still need to use workflow dispatches from Seam Connect -> TS SDK.

**Comment by sybohy** [comment]
is there any reason we care for the SDK tests to be private?

**Comment by codetheweb** [comment]
The reasoning was that they expose some of the implementation details of Seam Connect. It's not anything too bad, but it would feel a little weird (to me) to make them public without Connect being OSS. Mostly stuff like internal APIs (aren't really "private", users can sniff their traffic to see what we're doing) and database schemas.

**Comment by sybohy** [comment]
@seveibar can make the call I suppose. I'm fine with whichever decision. We sell to fairly technical folks. If they want to know the inner details, they will find a way.

**Comment by seveibar** [comment]
@codetheweb the flow you proposed makes a lot of sense! I would copy the private to public pattern that is established here for seamapi/python if we did it- the submodule pattern seemed tricky to me.

I think it's probably not a good idea to expose too many implementation details but @sybohy is right that exposing right now isn't too big of a deal and doesn't matter too much in this repo. There are scenarios where things get messy though, for example, we have development-time dependencies on third party services (e.g. clerk.dev, device providers), and it's possible those development-time credentials could be exposed in github action logging for complex setups with DEBUG enabled (e.g. in axios logging)

Overall, I think @codetheweb's approach (especially if we establish a pattern) will be easier in the long-term and help us sleep at night (mostly b/c GA logging). But I'm not opposed to the short-term solution of dropping tests in here.

**Comment by codetheweb** [comment]
Will merge tests into this repo for now.
